# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://app.vagrantup.com/hashicorp/boxes/bionic64
  config.vm.box = "hashicorp/bionic64"

  config.vm.box_check_update = true

  # Forwarded ports
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
  config.vm.network "forwarded_port", guest: 22, host: 2000 # Master Node SSH
  config.vm.network "forwarded_port", guest: 6443, host: 6443 # API Access
  for p in 30000..32767 # expose NodePort IP's
    config.vm.network "forwarded_port", guest: p, host: p, protocol: "tcp"
  end

  # Create a private network, which allows host-only access to the machine
  # IP will be assigned by DHCP.
  config.vm.network "private_network", type: "dhcp"

  # Customize hostname of the guestVM
  config.vm.hostname = "k3d-cluster"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the guest VM:
    vb.cpus = 2
    vb.memory = "4096"
    vb.name = "k3d box"
  end

  # Enable provisioning guest VM with shell script
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    # Install Docker
    # Reference: https://docs.docker.com/engine/install/ubuntu/
    apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    apt-key fingerprint 0EBFCD88
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    apt-get update -y
    apt-get install -y docker-ce docker-ce-cli containerd.io

    # Install k3d
    # Reference: https://github.com/rancher/k3d
    wget -q -O - https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash

    # Install kubectl
    curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    mv kubectl /usr/local/bin/
    chmod +x /usr/local/bin/kubectl

    # install helm 3
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    helm repo add stable https://charts.helm.sh/stable

    # Bash Completion for kubectl - very handy
    #apt-get install -y bash-completion
    #echo "source <(kubectl completion bash)" >> ~/.bashrc
    #source ~/.bashrc

    # Aliases
    #alias k='kubectl'

    # Install Portainer
    docker volume create portainer_data
    docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
    echo "Portainer portal can be reached through https://$(hostname -I | awk '{ print $2 }'):9443"


    # Add vagrant user to docker group (Running docker command without sudo)
    addgroup -a vagrant docker
    echo "DHCP has provided the following IP: $(hostname -I | awk '{ print $2 }')"
  SHELL
end
